ArmaRealMapWebSite/Controllers/AceWeatherController.cs
using System.Threading.Tasks;
using ArmaRealMapWebSite.Models;
using GameRealisticMap.Arma3.GameEngine.Extensions;
using GameRealisticMap.Nature.Weather;
using Microsoft.AspNetCore.Mvc;
using WeatherStats.Databases;

namespace ArmaRealMapWebSite.Controllers
{
    public class AceWeatherController : Controller
    {
        [HttpGet]
        public async Task<IActionResult> Index(string coordinates = null)
        {
            if ( !string.IsNullOrWhiteSpace(coordinates) )
            {
                return await Index(new AceWeatherModel() { Coordinates = coordinates });
            }
            return View(new AceWeatherModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(AceWeatherModel model)
        {
            if (!CoordinateSharp.Coordinate.TryParse(model.Coordinates, out var coordinate))
            {
                ModelState.AddModelError(nameof(model.Coordinates), "Invalid coordinates");
                return View(model);
            }
            var db = WeatherStatsDatabase.Create("https://weatherdata.pmad.net/ERA5AVG/");
            var data = await db.GetStats(coordinate.Latitude.ToDouble(), coordinate.Longitude.ToDouble());
            if (data == null)
            {
                ModelState.AddModelError(nameof(model.Coordinates), "No data for those coordinates");
                return View(model);
            }
            model.RawData = data;
            model.AceConfig = AceWeather.GenerateWeather(new WeatherData(data));
            return View(model);
        }
    }
}

ArmaRealMapWebSite/Controllers/AuthenticationController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using ArmaRealMapWebSite.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.DependencyInjection;

namespace ArmaRealMapWebSite.Controllers
{
    public class AuthenticationController : Controller
    {

        [HttpGet]
        public async Task<IActionResult> SignIn(string ReturnUrl)
        {
            if (ReturnUrl != null && !ReturnUrl.StartsWith("/"))
            {
                return BadRequest();
            }
            var vm = new SignInViewModel();
            vm.ReturnUrl = ReturnUrl ?? "/Home/Index";
            vm.Providers = await GetExternalProvidersAsync(HttpContext);
            return View("SignIn", vm);
        }

        [HttpPost]
        public async Task<IActionResult> SignIn([FromForm] string provider, [FromForm] bool isPersistent, [FromForm] string ReturnUrl)
        {
            // Note: the "provider" parameter corresponds to the external
            // authentication provider choosen by the user agent.
            if (string.IsNullOrWhiteSpace(provider))
            {
                return BadRequest();
            }

            if (!await IsProviderSupportedAsync(HttpContext, provider))
            {
                return BadRequest();
            }

            if (!ReturnUrl.StartsWith("/"))
            {
                return BadRequest();
            }

            // Instruct the middleware corresponding to the requested external identity
            // provider to redirect the user agent to its own authorization endpoint.
            // Note: the authenticationScheme parameter must match the value configured in Startup.cs
            return Challenge(new AuthenticationProperties { RedirectUri = ReturnUrl, IsPersistent = isPersistent }, provider);
        }

        [HttpGet, HttpPost]
        public new IActionResult SignOut()
        {
            // Instruct the cookies middleware to delete the local cookie created
            // when the user agent is redirected from the external identity provider
            // after a successful authentication flow (e.g Google or Facebook).
            return SignOut(new AuthenticationProperties { RedirectUri = "/Home/Index" },
                CookieAuthenticationDefaults.AuthenticationScheme);
        }
        public static async Task<AuthenticationScheme[]> GetExternalProvidersAsync(HttpContext context)
        {
            if (context == null)
            {
                throw new ArgumentNullException(nameof(context));
            }

            var schemes = context.RequestServices.GetRequiredService<IAuthenticationSchemeProvider>();

            return (from scheme in await schemes.GetAllSchemesAsync()
                    where !string.IsNullOrEmpty(scheme.DisplayName)
                    select scheme).ToArray();
        }

        public static async Task<bool> IsProviderSupportedAsync(HttpContext context, string provider)
        {
            if (context == null)
            {
                throw new ArgumentNullException(nameof(context));
            }

            return (from scheme in await GetExternalProvidersAsync(context)
                    where string.Equals(scheme.Name, provider, StringComparison.OrdinalIgnoreCase)
                    select scheme).Any();
        }

        public IActionResult Denied() => View("Denied");

    }
}

ArmaRealMapWebSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Game Realistic Map</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://kit.fontawesome.com/bcf9eaf5ce.js" crossorigin="anonymous" async="async"></script>
    @await RenderSectionAsync("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Game Realistic Map</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AceWeather" asp-action="Index">ACE3 Weather</a>
                        </li>
                    </ul>
                    <form class="form-inline">
                        @if (User?.Identity?.IsAuthenticated ?? false)
                        {
                            <span class="mr-sm-2" style="font-size:80%">@User.Identity.Name</span>
                            <a asp-controller="Authentication" asp-action="SignOut" class="btn btn-sm btn-secondary" title="@User.Identity.Name">Disconnect</a>
                        }
                        else
                        {
                            <a asp-controller="Authentication" asp-action="SignIn" class="btn btn-sm btn-secondary">Connect</a>
                        }
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            Tool by <a href="https://pmad.net/">GrueArbre</a> - <a href="https://pmad.net/privacy.html">Privacy</a>.<br />
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>